mumuki/mumuki-gobstones-runner

- .gitignore
- .travis.yml
- README.md
- config/development.yml
- config/production.yml
- lib/checker.rb
- lib/expectations_hook.rb
- lib/gobstones_runner.rb
- spec/expectations_spec.rb
I found some problems here: https://github.com/mumuki/mulang/issues/51
> Expectations hook

- lib/assets_server.rb
- lib/checker.rb
- lib/gobstones/batch_parser.rb
- spec/metatest_spec.rb
Fixes https://github.com/mumuki/mumuki-gobstones-runner/issues/15
Fixes https://github.com/mumuki/mumuki-gobstones-runner/issues/16
> Fix final board postcondition

- lib/expectations_hook.rb
- spec/integration_spec.rb
> Issue#32 auto add declares binding for subject

- lib/precompile_hook.rb
- spec/integration_spec.rb
> Issue#39 auto add missing headers

- lib/expectations_hook.rb
- spec/integration_spec.rb
> adding smell exclusions

- lib/assets_server.rb
> Set Access-Control-Allow-Origin to *

- lib/precompile_hook.rb
- lib/render/html_renderer.rb
- mumuki-gobstones-runner.gemspec
- spec/integration_spec.rb
> adding support for show_initial_board: false

- README.md
- lib/metadata_hook.rb
> Documenting gobstones spec syntax in the README and adding template in metadata hook

- lib/render/html_renderer.rb
- spec/integration_spec.rb
> FIX: Ignoring unexisting board types from the response - Fixes #64

- lib/assets_server.rb
- lib/gobstones.rb
- lib/gobstones/batch.rb
- lib/gobstones_runner.rb
- lib/render/editor/editor.css
- lib/render/editor/editor.html
- lib/render/editor/editor.js
- mumuki-gobstones-runner.gemspec
- spec/precompile_spec.rb
- worker/Dockerfile
Related to https://github.com/mumuki/mumuki-gobstones-runner/issues/59
Fixes #60 
Fixes #62
Updated video: https://www.youtube.com/watch?v=SgwpoyzuXgs
> Adding gobstones-code-runner integration

- lib/assets_server.rb
- lib/render/boards.html.erb
> exposing boom.png in assets path

- lib/render/editor/editor.html
Resolves https://github.com/mumuki/mumuki-laboratory/issues/992
> slowing the execution of the interpreter

- README.md
Resolves #75 
@flbulgarelli Now it's ready to merge :bowtie:
> adding some kids tests considerations

- lib/render/editor/editor.html
- lib/render/editor/editor.js
Here i'm relying in paper-fab that's imported by gobstones-code-runner.
Adding the inclusion in this element would require using bower and introducing this element inside gobstones-code-runner doesn't quite feel right.
> adding reset-content button

- lib/render/editor/editor.html
Resolves https://github.com/mumuki/mumuki-bibliotheca/issues/139
> adding explicit call to onresize on initialize

- lib/gobstones/batch.rb
- mumuki-gobstones-runner.gemspec
- spec/integration_spec.rb
- spec/precompile_spec.rb
I found a bug doing it :smile: (expectations weren't working well). It's fixed now.
I also updated gobstones-board to `1.15` which adds support for screen readers.
> Testing exercises with XML as input - Fixes #74 - Fixes #57

- lib/render/editor/editor.html
Resolves https://github.com/mumuki/mumuki-laboratory/issues/974
> adding trash canvas in editor

- lib/render/editor/editor.html
Merge after https://github.com/mumuki/mumuki-laboratory/pull/1029/files
> using new kids functions defined in labo

- lib/render/editor/editor.html
> returning aborted status when submissions fails

- lib/render/editor/editor.html
Merge after https://github.com/mumuki/mumuki-laboratory/pull/1037
> resetting status after aborted

- lib/render/editor/editor.html
Fixes https://github.com/mumuki/mumuki-laboratory/issues/1050
Setting primitiveProcedures again when toolbox is updated
> Fixing primitive procedures

- lib/render/editor/editor.html
Fixes #108 
Fixes https://github.com/mumuki/mumuki-bibliotheca/issues/149
> Fixing default code - Fixes #108

- lib/render/editor/editor.html
> relocating trash only if not in readOnly mode

- lib/render/boards.html.erb
- spec/integration_spec.rb
Related to https://github.com/mumuki/mumuki-laboratory/issues/1051
> Dont show head on exercises that dont check it

- lib/render/editor/editor.html
- lib/render/editor/editor.js
This fix prevents this from happening:
> waiting for Blockly to be defined before settings sounds

- lib/assets_server.rb
- lib/public/attires_disabled.svg
- lib/public/attires_enabled.svg
- lib/render/editor/editor.html
- lib/render/editor/editor.js
Fixes https://github.com/mumuki/mumuki-laboratory/issues/1086
https://youtu.be/2z9QquudXZc
Ok sí la UI necesita amor. @fedescarpa qué idea tenían acá?
> Adding attire toggle button - Fixes mumuki/mumuki-laboratory#1086

- lib/render/editor/editor.html
I don't like this approach at all, so if you have a better one please change it @rodri042 
Resolves #119
> hiding button if no attires present

- lib/render/editor/editor.html
- mumuki-gobstones-runner.gemspec
Fixes https://github.com/mumuki/mumuki-laboratory/issues/1210
> Fixing toolbox assignment - Fixes mumuki/mumuki-laboratory#1210

- lib/precompile_hook.rb
- lib/render/editor/editor.html
Fixes https://github.com/mumuki/mumuki-gobstones-runner/pull/125
Related with https://github.com/mumuki/mumuki-laboratory/pull/1214
> Expect endless while kids - Fixes #125

- lib/render/editor/editor.css
Fixes mumuki/mumuki-laboratory#1217
Demo @ https://youtu.be/fhEOC49d8uM
> Fixing initial board shrinking - Fixes mumuki/mumuki-laboratory#1217

- lib/render/boards.html.erb
Fixes https://github.com/mumuki/mumuki-gobstones-runner/issues/131
> Hide head only in expected board - Fixes #131

- lib/render/editor/editor.html
- mumuki-gobstones-runner.gemspec
Resolves #136 
:warning: Merge after https://github.com/gobstones/gs-board/pull/21 :warning:
> using events to set attire toggle button visibility

- lib/render/editor/editor.html
Fixes #143
It was only showing up when it was enabled (https://youtu.be/ZThrsKHwr-M)
> Fixing attire toggle - Fixes #143

- lib/render/boards.html.erb
- lib/render/editor/editor.css
- lib/render/editor/editor.html
- lib/render/editor/editor.js
> support for multiple scenarios

- lib/checker.rb
- spec/integration_spec.rb
> Chore wrong argument type fix

- lib/render/editor/editor.html
- lib/render/editor/editor.js
Related to https://github.com/mumuki/mumuki-laboratory/issues/982
Related to https://github.com/mumuki/mumuki-laboratory/pull/1287
> Feature laboratory 6.5 api

- lib/render/editor/editor.html
> getting gbb from board to make it work properly on Chrome

- lib/render/editor/editor.html
> Scrolling to block before showing errors - #161

- lib/assets_server.rb
- lib/render/editor/editor.html
- mumuki-gobstones-runner.gemspec
Resolves #166 and avoids making the toolbox request if the main editor is readOnly
> Using with_assets mixin from mumukit

- lib/gobstones/batch.rb
- lib/gobstones/example_code_builder.rb
- lib/gobstones_runner.rb
- spec/integration_spec.rb
- spec/precompile_spec.rb
- worker/Dockerfile
Fixes https://github.com/mumuki/mumuki-gobstones-runner/issues/168
Related issue: https://github.com/gobstones/gobstones-cli/issues/11
Related PR: https://github.com/gobstones/gobstones-cli/pull/13
> Fixing exercises with subject using gobstones-cli@4.0.0 -  Fixes #168

- lib/metadata_hook.rb
- lib/render/editor/editor.html
I've added it in a backwards compatible manner
> Calling mumuki.assetsLoaderFor when the toolbox has finished loading

- Gemfile
- lib/checker.rb
- lib/render/html_renderer.rb
- lib/render/with_renderer.rb
- mumuki-gobstones-runner.gemspec
- spec/integration_spec.rb
Depends on https://github.com/mumuki/mumukit/pull/103
Depends on https://github.com/mumuki/mumukit/pull/104
Depends on https://github.com/mumuki/mumukit-bridge/pull/20
> Feature expose summary

- README.md
- devinit
- devstart
- lib/render/editor/editor.html
- mumuki-gobstones-runner.gemspec
Closes #182 
:warning: Build will fail until https://github.com/mumuki/gs-element-blockly/pull/2 is merged and version `0.36.0` is released.
Depends on https://github.com/mumuki/mumuki-laboratory/pull/1455
> Support toolbox without categories

- lib/assets_server.rb
- lib/render/editor/editor.html.erb
> Chore fixes to teacher code

- lib/gobstones_runner.rb
- mumuki-gobstones-runner.gemspec
- spec/expectations_spec.rb
- worker/Dockerfile
To update mulang and friends to version 6
> Chore mulang 6

- lib/expectations_hook.rb
- mumuki-gobstones-runner.gemspec
- spec/expectations_spec.rb
To provide autocorrection rules for the Gobstones language
> Implement autocorrection rules

- config/development.yml
- config/production.yml
- lib/expectations_hook.rb
- lib/gobstones_runner.rb
- mumuki-gobstones-runner.gemspec
- spec/expectations_spec.rb
- worker/Dockerfile
To make runner work with mulang 6.10 operators
> Update mulang 6.10
