- .gitignore
- .travis.yml
- README.md
- bower.json
- lib/boards.html.erb
- lib/dynamic_load_html.js
- lib/html_renderer.rb
Depends on https://github.com/mumuki/mumuki-gobstones-runner/pull/4 ([diffs](https://github.com/mumuki/mumuki-gobstones-runner/compare/boom-postcondition...support-board-offline))
Related: https://github.com/gobstones/gs-board/commit/c9888bff1e5311bbec7118fa2383ec57ed7ea3cf and https://github.com/gobstones/gs-board/commit/86f91a15a257cea4f38ccb7b7d05057c0aa6ec0a
Now the runner returns in the output all the necessary things to work. The `dynamic_load_html.js` file does what a html import would do if there's no internet connection (meh). Really, the html import guarantees idempotency (it won't add the html or execute the scripts twice) and I've to add a few flags for the cases when the code is already loaded on Atheneum (i.e. the student runs an exercise for second time).
The polymer code …
> Offline support of GW board

- lib/checker.rb
- lib/gobstones/batch_parser.rb
- spec/integration_spec.rb
- spec/metatest_spec.rb
- spec/test_runner_spec.rb
@flbulgarelli I've been testing and now I can confirm that the test was wrong. Maybe it was working accidentally using a previous version of `mumukit-inspection`
For the code:
```
procedure PonerUnaDeCada() {
Poner (Rojo)
Poner (Azul)
Poner (Negro)
Poner (Verde)
}
```
The expectation:
```js
{  binding: 'PonerUnaDeCada', inspection: 'HasUsage' }
```
caused the bug.
[All the guide exercises](https://github.com/search?q=org%3Asagrado-corazon-alcal+HasUsage&type=Code) use this other form:
```js
{ binding: 'program', inspection: 'HasUsage:PonerUnaDeCada' }
```
---
I think the only case where the binding and target are inverted is `HasBinding` and `mumukit-inspection` is already handling it. So I only needed to update the tests assertions because now the results are given with the new format. …
> Failing spec - Fixes #19 - Fixes #21

- lib/assets_server.rb
- lib/render/editor/editor.html
- lib/render/editor/editor.js
@rodri042 I had to do the insertion in editor.js because otherwise it wasn't called again when navigating between pages
> Defining a local wrapper for gs-element-blockly and updating editor.js

- lib/render/editor/editor.html
- mumuki-gobstones-runner.gemspec
This PR addresses some issues that @flbulgarelli found with kids layout.
Now teacher procedures are working now, the problem was that `gs-element-blockly` was doing some weird things to parse the custom toolbox (specifically, splitting the XML string by newlines and matching category blocks with regexps) and it wasn't working with `<category name="Procedimientos primitivos"></category>` instead of `<category name="Procedimientos primitivos">\n</category>`.
Regarding the colors, I added a few missing color mappings, and code for setting the colors on the first load (since the default code loads before applying the custom colors).
Updating `gobstones-board` and drawing a board without head worked for me :confused: 
I used this as an exercise's description: `"prueba sin header: <gs-board …
> Updating gobstones components

- .gitignore
- lib/gobstones_runner.rb
- spec/integration_spec.rb
- worker/Dockerfile
Fixing failing inspections for Mulang ASTs that included the - now outdated - `MuNull` element. 
Depends on: https://github.com/gobstones/gobstones-cli/pull/5
> Fixing failing inspections

- lib/render/editor/editor.html
Fixes #114 
This PR addresses the #114 problem that only happens on Firefox. I couldn't figure out why if we assign the initial code at the very beginning, `gs-element-blockly` replaces the code with an empty program.
> Delaying the initial code assignment to fix firefox bug - Fixes #114

- lib/checker.rb
- lib/precompile_hook.rb
- lib/render/editor/editor.html
Fixes https://github.com/mumuki/mumuki-laboratory/issues/1207
Este PR es sobre los errores:
1) > Otro problema más raro aún es que en https://mumuki.io/primaria/exercises/5589-repeticion-condicional-practica-al-infinito, si se envíe el código tal cual está, da verde (pero debería fallar, porque falta un bloque)
Esto sucedía por varios problemas:
- gobstones-blockly generaba `while(not(())) { ... }` con el código en cuestión
- `()` es una tupla vacía en XGobstones
- `not` de una tupla vacía es un error en tiempo de ejecución, da boom
- El ejercicio tenía un solo `initial_board` pero ningún test, entonces no rompía. Si hubiera sido:
```
expect_endless_while: true
check_head_position: false
examples:
- initial_board: |
GBB/1.0
size 2 2
cell 0 1 Negro 4 Rojo 4 
cell 1 1 Azul 6 Rojo 4 
cell 0 …
```
> Checking expected timeouts on check_error too -  Fixes mumuki/mumuki-laboratory#1207

- lib/gobstones_runner.rb
- mumuki-gobstones-runner.gemspec
- worker/Dockerfile
@flbulgarelli 
Este PR actualiza todo a sus últimas versiones.
Los breaking changes que vi que afectan a mumuki son:
- La recursión está desactivada por default, o sea que `program { Foo() } procedure Foo() { Foo() }` no anda más (digamos, en vez de pinchar por "ocurrió un timeout" ahora lo hace por "usaste recursión y no se puede :policeman:"). Se puede volver al comportamiento anterior agregando `/*@LANGUAGE@AllowRecursion@*/` en cualquier lado.
- Hubo un rename de `ultimo` a `último` en el idioma español
Esos dos cambios los manejé acá (https://github.com/gobstones/gobstones-cli/commit/a3f84e8ea9e860f0a0ad687865b1d7dece8c9cf2) así que del lado del runner no hay mucho que cambiar. Otra cosa que estaba fea es que si encontraba alguna estructura no soportada en el AST de mulang, rompía …
> Updating interpreter version

- lib/render/editor/editor.html
The problematic exercise was generating this code:
(one of the instructions has an id that starts with `*/`, which closes the region pragma and causes a syntax error).
I've removed the `/` as a valid character for block ids so this can't happen again. The fix was applied in `gobstones-blockly` code as well, but since the last versions have some breaking changes, I decided not to update the component yet.
This won't make the problematic solutions work as they already have invalid block ids.
> Preventing invalid block ids

- lib/render/editor/editor.html
This fixes the fact that the non-visible boards weren't being updated.
> extracting gbb before initializing node

- lib/metadata_hook.rb
- lib/render/editor/editor.html
I added it on a retrocompatible manner, so that this could work without the mumuki.assetsServer object.
> adding shows_loading_content for editor assets and calling onFinishLoading

- lib/render/editor/editor.html
In some weird cases, mumuki object isn't defined before that function is executed and the loader doesn't stop.
> Ensuring that mumuki.assetsLoadedFor is defined

- lib/assets_server.rb
- lib/metadata_hook.rb
- lib/render/editor/editor.html
- lib/render/layout/layout.html
This doesn't solve the problem entirely, cuz there's a bug in gs-board that causes the boards to not render the attires if they are attached after the assets are loaded.
> Moving attires component to layout asset

- lib/render/editor/editor.html.erb
The goal of this PR is to allow using a different - experimental - kindergarten color without affecting backwards compatibility. 
This PR exist only for adding backward compatibility lost in #191
> Green color  takes effect in kindergarten's repeat only

- lib/checker.rb
- lib/render/boards.html.erb
- lib/render/html_renderer.rb
- spec/metatest_spec.rb
Removing board title. This change requires changes introduced in https://github.com/mumuki/mumuki-laboratory/pull/1399.
Although this PR is compatible with previous versions of laboratory, titles won't be displayed.
> Removing board title

- lib/assets_server.rb
- lib/game_framework/default.gbs.erb
- lib/game_framework/default.xml.erb
- lib/gobstones/compilation_mode.rb
- lib/render/editor/editor.html.erb
This adds support for automatic default change on Bibliotheca. The default code of the game framework is configured when an editor changes layout to kindergarten.
> Feature game framework default code

- lib/render/editor/editor.html.erb
To decouple game framework - which was designed as layout agnostic - activation from `kindergarten`. That way `primary` exercises and even text exercises will be able to use `game_framework`, and `kindergarten` exercises will not be forced to do that. 
* Related to https://github.com/mumuki/mumuki-laboratory/pull/1467
* https://github.com/mumuki/mumuki-gobstones-runner/pull/195#issuecomment-690670114
> Feature use settings instead of layout for game-framework

- lib/game_framework/extra.gbs.erb
- lib/render/editor/editor.css
- spec/integration_spec.rb
To always show board on kindergarten, even on `boom`, and allow content editors to represent boom situations using the gobstones attires mappings. 
I had to force style with an important since board hiding is being performed programatically by gobstones cli using an inline style :shrug:. 
Also, I had to change game framework to manually set overlay  right before `boom`. The downside is that won't allow showing an intermediate state of _i have just arrived to the obstacle, and I am about to collide_
Rebase after #198
This gif shows what happens when the `actor` :red_circle: passes through the `obstacle` `object` :two: :large_blue_circle: : program just stops - :two: :green_circle: - and no boom :boom: is displayed.
> Feature kindergarten boom

- lib/render/editor/editor.html.erb
This PR fixes miscellaneous classroom bugs related with toolbox initialization in read-only contexts
The main problem was that new code was not properly handling the `readOnly` flag, causing errors to arise and preventing workspace to be actually initialized. The main fix is to avoid setting a toolbox in read-only mode, but still allowing workspace to be initialized. The rest is refactoring
1. I have delegated into `configureCustomToolboxFromUrl` the async process of loading a toolbox
2. I have augmented `hasCustomToolbox` to only consider editable workspaces
3. I have extracted two very explicit methods for initializing workspace with and without a custom toolbox: `_initializeCustomToolboxBlocklyWorkspace` and `_initializeNonCustomToolboxBlocklyWorkspace`
4. As a side improvement, now …
> Chore dont set toolbox when readonly

- lib/render/editor/editor.html.erb
Ignore the nasty tooltip errors with some monkeypatching :monkey: .
> All the captures have been taken with `debug` (`verbose`) mode on
We should instead PR this to `gs-element-blockly`
> Chore swallow tooltip errors

- lib/render/editor/editor.html.erb
To fix trash relocation errors
The problem was that a call to `_relocateTrash` after initializing the workspace was missing
> Fix #213 trash does not appear on kindergarten

- lib/render/editor/editor.css
- lib/render/editor/editor.html.erb
To hide bubble on kindergarten exercises, in order to reduce text prompts. 
This PR hides blockly bubble in kinder only. I initially thought about making this work for game framework, but it is not a problem style issue, but a layout issue.
> Feature hide bubble on kindergarten
